// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: gerti.proto

package gerti

import (
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type NewNodeType int32

const (
	NewNodeType_Initial    NewNodeType = 0
	NewNodeType_Assignment NewNodeType = 1
	NewNodeType_Announce   NewNodeType = 2
	NewNodeType_Stored     NewNodeType = 3
)

// Enum value maps for NewNodeType.
var (
	NewNodeType_name = map[int32]string{
		0: "Initial",
		1: "Assignment",
		2: "Announce",
		3: "Stored",
	}
	NewNodeType_value = map[string]int32{
		"Initial":    0,
		"Assignment": 1,
		"Announce":   2,
		"Stored":     3,
	}
)

func (x NewNodeType) Enum() *NewNodeType {
	p := new(NewNodeType)
	*p = x
	return p
}

func (x NewNodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NewNodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_gerti_proto_enumTypes[0].Descriptor()
}

func (NewNodeType) Type() protoreflect.EnumType {
	return &file_gerti_proto_enumTypes[0]
}

func (x NewNodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NewNodeType.Descriptor instead.
func (NewNodeType) EnumDescriptor() ([]byte, []int) {
	return file_gerti_proto_rawDescGZIP(), []int{0}
}

type NewNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type NewNodeType `protobuf:"varint,1,opt,name=Type,proto3,enum=gerti.NewNodeType" json:"Type,omitempty"`
	// Types that are assignable to Content:
	//	*NewNode_Data
	//	*NewNode_None
	Content isNewNode_Content `protobuf_oneof:"Content"`
}

func (x *NewNode) Reset() {
	*x = NewNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerti_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewNode) ProtoMessage() {}

func (x *NewNode) ProtoReflect() protoreflect.Message {
	mi := &file_gerti_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewNode.ProtoReflect.Descriptor instead.
func (*NewNode) Descriptor() ([]byte, []int) {
	return file_gerti_proto_rawDescGZIP(), []int{0}
}

func (x *NewNode) GetType() NewNodeType {
	if x != nil {
		return x.Type
	}
	return NewNodeType_Initial
}

func (m *NewNode) GetContent() isNewNode_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *NewNode) GetData() *NewNodeData {
	if x, ok := x.GetContent().(*NewNode_Data); ok {
		return x.Data
	}
	return nil
}

func (x *NewNode) GetNone() *empty.Empty {
	if x, ok := x.GetContent().(*NewNode_None); ok {
		return x.None
	}
	return nil
}

type isNewNode_Content interface {
	isNewNode_Content()
}

type NewNode_Data struct {
	Data *NewNodeData `protobuf:"bytes,2,opt,name=Data,proto3,oneof"`
}

type NewNode_None struct {
	None *empty.Empty `protobuf:"bytes,3,opt,name=None,proto3,oneof"`
}

func (*NewNode_Data) isNewNode_Content() {}

func (*NewNode_None) isNewNode_Content() {}

type NewNodeData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Tier    int32  `protobuf:"varint,2,opt,name=Tier,proto3" json:"Tier,omitempty"`
}

func (x *NewNodeData) Reset() {
	*x = NewNodeData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerti_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewNodeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewNodeData) ProtoMessage() {}

func (x *NewNodeData) ProtoReflect() protoreflect.Message {
	mi := &file_gerti_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewNodeData.ProtoReflect.Descriptor instead.
func (*NewNodeData) Descriptor() ([]byte, []int) {
	return file_gerti_proto_rawDescGZIP(), []int{1}
}

func (x *NewNodeData) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NewNodeData) GetTier() int32 {
	if x != nil {
		return x.Tier
	}
	return 0
}

type RegisterNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip   string `protobuf:"bytes,1,opt,name=Ip,proto3" json:"Ip,omitempty"`
	Tier int32  `protobuf:"varint,2,opt,name=Tier,proto3" json:"Tier,omitempty"`
}

func (x *RegisterNode) Reset() {
	*x = RegisterNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerti_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNode) ProtoMessage() {}

func (x *RegisterNode) ProtoReflect() protoreflect.Message {
	mi := &file_gerti_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNode.ProtoReflect.Descriptor instead.
func (*RegisterNode) Descriptor() ([]byte, []int) {
	return file_gerti_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterNode) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RegisterNode) GetTier() int32 {
	if x != nil {
		return x.Tier
	}
	return 0
}

type RegisterComplete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetIp     string `protobuf:"bytes,1,opt,name=TargetIp,proto3" json:"TargetIp,omitempty"`
	GERTiAddress string `protobuf:"bytes,2,opt,name=GERTiAddress,proto3" json:"GERTiAddress,omitempty"`
}

func (x *RegisterComplete) Reset() {
	*x = RegisterComplete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerti_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterComplete) ProtoMessage() {}

func (x *RegisterComplete) ProtoReflect() protoreflect.Message {
	mi := &file_gerti_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterComplete.ProtoReflect.Descriptor instead.
func (*RegisterComplete) Descriptor() ([]byte, []int) {
	return file_gerti_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterComplete) GetTargetIp() string {
	if x != nil {
		return x.TargetIp
	}
	return ""
}

func (x *RegisterComplete) GetGERTiAddress() string {
	if x != nil {
		return x.GERTiAddress
	}
	return ""
}

type RemoveNeighborData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
}

func (x *RemoveNeighborData) Reset() {
	*x = RemoveNeighborData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerti_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveNeighborData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNeighborData) ProtoMessage() {}

func (x *RemoveNeighborData) ProtoReflect() protoreflect.Message {
	mi := &file_gerti_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNeighborData.ProtoReflect.Descriptor instead.
func (*RemoveNeighborData) Descriptor() ([]byte, []int) {
	return file_gerti_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveNeighborData) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CloseConnectionData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConnectDex string `protobuf:"bytes,1,opt,name=ConnectDex,proto3" json:"ConnectDex,omitempty"`
}

func (x *CloseConnectionData) Reset() {
	*x = CloseConnectionData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerti_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseConnectionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseConnectionData) ProtoMessage() {}

func (x *CloseConnectionData) ProtoReflect() protoreflect.Message {
	mi := &file_gerti_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseConnectionData.ProtoReflect.Descriptor instead.
func (*CloseConnectionData) Descriptor() ([]byte, []int) {
	return file_gerti_proto_rawDescGZIP(), []int{5}
}

func (x *CloseConnectionData) GetConnectDex() string {
	if x != nil {
		return x.ConnectDex
	}
	return ""
}

type OpenRoute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dest         string `protobuf:"bytes,1,opt,name=Dest,proto3" json:"Dest,omitempty"`
	Intermediary string `protobuf:"bytes,2,opt,name=Intermediary,proto3" json:"Intermediary,omitempty"`
	Origin       string `protobuf:"bytes,3,opt,name=Origin,proto3" json:"Origin,omitempty"`
	ID           int32  `protobuf:"varint,4,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *OpenRoute) Reset() {
	*x = OpenRoute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerti_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRoute) ProtoMessage() {}

func (x *OpenRoute) ProtoReflect() protoreflect.Message {
	mi := &file_gerti_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRoute.ProtoReflect.Descriptor instead.
func (*OpenRoute) Descriptor() ([]byte, []int) {
	return file_gerti_proto_rawDescGZIP(), []int{6}
}

func (x *OpenRoute) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

func (x *OpenRoute) GetIntermediary() string {
	if x != nil {
		return x.Intermediary
	}
	return ""
}

func (x *OpenRoute) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *OpenRoute) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

type RouteOpen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Origin    string `protobuf:"bytes,1,opt,name=Origin,proto3" json:"Origin,omitempty"`
	PktDesk   string `protobuf:"bytes,2,opt,name=PktDesk,proto3" json:"PktDesk,omitempty"`
	PktOrigin string `protobuf:"bytes,3,opt,name=PktOrigin,proto3" json:"PktOrigin,omitempty"`
}

func (x *RouteOpen) Reset() {
	*x = RouteOpen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerti_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteOpen) ProtoMessage() {}

func (x *RouteOpen) ProtoReflect() protoreflect.Message {
	mi := &file_gerti_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteOpen.ProtoReflect.Descriptor instead.
func (*RouteOpen) Descriptor() ([]byte, []int) {
	return file_gerti_proto_rawDescGZIP(), []int{7}
}

func (x *RouteOpen) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *RouteOpen) GetPktDesk() string {
	if x != nil {
		return x.PktDesk
	}
	return ""
}

func (x *RouteOpen) GetPktOrigin() string {
	if x != nil {
		return x.PktOrigin
	}
	return ""
}

type DataPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data       *any.Any `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	ConnectDex string   `protobuf:"bytes,2,opt,name=ConnectDex,proto3" json:"ConnectDex,omitempty"`
	Order      int32    `protobuf:"varint,3,opt,name=Order,proto3" json:"Order,omitempty"`
	Origin     string   `protobuf:"bytes,4,opt,name=Origin,proto3" json:"Origin,omitempty"`
}

func (x *DataPacket) Reset() {
	*x = DataPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerti_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPacket) ProtoMessage() {}

func (x *DataPacket) ProtoReflect() protoreflect.Message {
	mi := &file_gerti_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPacket.ProtoReflect.Descriptor instead.
func (*DataPacket) Descriptor() ([]byte, []int) {
	return file_gerti_proto_rawDescGZIP(), []int{8}
}

func (x *DataPacket) GetData() *any.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataPacket) GetConnectDex() string {
	if x != nil {
		return x.ConnectDex
	}
	return ""
}

func (x *DataPacket) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *DataPacket) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

var File_gerti_proto protoreflect.FileDescriptor

var file_gerti_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x67, 0x65, 0x72, 0x74, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x67,
	0x65, 0x72, 0x74, 0x69, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x94, 0x01, 0x0a,
	0x07, 0x4e, 0x65, 0x77, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x67, 0x65, 0x72, 0x74, 0x69, 0x2e, 0x4e,
	0x65, 0x77, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x28, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x67, 0x65, 0x72, 0x74, 0x69, 0x2e, 0x4e, 0x65, 0x77, 0x4e, 0x6f, 0x64, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x48, 0x00, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2c, 0x0a, 0x04, 0x4e, 0x6f,
	0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x48, 0x00, 0x52, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x22, 0x3b, 0x0a, 0x0b, 0x4e, 0x65, 0x77, 0x4e, 0x6f, 0x64, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x54, 0x69, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x54, 0x69, 0x65, 0x72,
	0x22, 0x32, 0x0a, 0x0c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x54, 0x69, 0x65, 0x72, 0x22, 0x52, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x49, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x54, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x49, 0x70, 0x12, 0x22, 0x0a, 0x0c, 0x47, 0x45, 0x52, 0x54, 0x69, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x47, 0x45, 0x52, 0x54,
	0x69, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x2e, 0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18,
	0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x35, 0x0a, 0x13, 0x43, 0x6c, 0x6f, 0x73,
	0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x1e, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x44, 0x65, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x44, 0x65, 0x78, 0x22,
	0x6b, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x44, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x65, 0x73, 0x74,
	0x12, 0x22, 0x0a, 0x0c, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x72, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6d, 0x65, 0x64,
	0x69, 0x61, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x22, 0x5b, 0x0a, 0x09,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x72, 0x69,
	0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x6b, 0x74, 0x44, 0x65, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x50, 0x6b, 0x74, 0x44, 0x65, 0x73, 0x6b, 0x12, 0x1c, 0x0a, 0x09, 0x50,
	0x6b, 0x74, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x50, 0x6b, 0x74, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x22, 0x84, 0x01, 0x0a, 0x0a, 0x44, 0x61,
	0x74, 0x61, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x44, 0x65, 0x78,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x44,
	0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x72, 0x69, 0x67,
	0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e,
	0x2a, 0x44, 0x0a, 0x0b, 0x4e, 0x65, 0x77, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0b, 0x0a, 0x07, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a,
	0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08,
	0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x64, 0x10, 0x03, 0x32, 0xa0, 0x03, 0x0a, 0x05, 0x47, 0x45, 0x52, 0x54, 0x69,
	0x12, 0x31, 0x0a, 0x0f, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x4e, 0x65, 0x77, 0x4e,
	0x6f, 0x64, 0x65, 0x12, 0x0e, 0x2e, 0x67, 0x65, 0x72, 0x74, 0x69, 0x2e, 0x4e, 0x65, 0x77, 0x4e,
	0x6f, 0x64, 0x65, 0x1a, 0x0e, 0x2e, 0x67, 0x65, 0x72, 0x74, 0x69, 0x2e, 0x4e, 0x65, 0x77, 0x4e,
	0x6f, 0x64, 0x65, 0x12, 0x38, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12,
	0x13, 0x2e, 0x67, 0x65, 0x72, 0x74, 0x69, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x4e, 0x6f, 0x64, 0x65, 0x1a, 0x17, 0x2e, 0x67, 0x65, 0x72, 0x74, 0x69, 0x2e, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x35, 0x0a,
	0x0b, 0x41, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x2e, 0x67,
	0x65, 0x72, 0x74, 0x69, 0x2e, 0x4e, 0x65, 0x77, 0x4e, 0x6f, 0x64, 0x65, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x34, 0x0a, 0x0e, 0x4f, 0x70, 0x65, 0x6e, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x2e, 0x67, 0x65, 0x72, 0x74, 0x69, 0x2e, 0x4f,
	0x70, 0x65, 0x6e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x1a, 0x10, 0x2e, 0x67, 0x65, 0x72, 0x74, 0x69,
	0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x12, 0x31, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x11, 0x2e, 0x67, 0x65, 0x72, 0x74, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x50,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x43, 0x0a,
	0x0e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x12,
	0x19, 0x2e, 0x67, 0x65, 0x72, 0x74, 0x69, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4e, 0x65,
	0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x12, 0x45, 0x0a, 0x0f, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x2e, 0x67, 0x65, 0x72, 0x74, 0x69, 0x2e, 0x43, 0x6c,
	0x6f, 0x73, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74,
	0x61, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x67,
	0x65, 0x72, 0x74, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gerti_proto_rawDescOnce sync.Once
	file_gerti_proto_rawDescData = file_gerti_proto_rawDesc
)

func file_gerti_proto_rawDescGZIP() []byte {
	file_gerti_proto_rawDescOnce.Do(func() {
		file_gerti_proto_rawDescData = protoimpl.X.CompressGZIP(file_gerti_proto_rawDescData)
	})
	return file_gerti_proto_rawDescData
}

var file_gerti_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gerti_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_gerti_proto_goTypes = []interface{}{
	(NewNodeType)(0),            // 0: gerti.NewNodeType
	(*NewNode)(nil),             // 1: gerti.NewNode
	(*NewNodeData)(nil),         // 2: gerti.NewNodeData
	(*RegisterNode)(nil),        // 3: gerti.RegisterNode
	(*RegisterComplete)(nil),    // 4: gerti.RegisterComplete
	(*RemoveNeighborData)(nil),  // 5: gerti.RemoveNeighborData
	(*CloseConnectionData)(nil), // 6: gerti.CloseConnectionData
	(*OpenRoute)(nil),           // 7: gerti.OpenRoute
	(*RouteOpen)(nil),           // 8: gerti.RouteOpen
	(*DataPacket)(nil),          // 9: gerti.DataPacket
	(*empty.Empty)(nil),         // 10: google.protobuf.Empty
	(*any.Any)(nil),             // 11: google.protobuf.Any
}
var file_gerti_proto_depIdxs = []int32{
	0,  // 0: gerti.NewNode.Type:type_name -> gerti.NewNodeType
	2,  // 1: gerti.NewNode.Data:type_name -> gerti.NewNodeData
	10, // 2: gerti.NewNode.None:type_name -> google.protobuf.Empty
	11, // 3: gerti.DataPacket.Data:type_name -> google.protobuf.Any
	1,  // 4: gerti.GERTi.AnnounceNewNode:input_type -> gerti.NewNode
	3,  // 5: gerti.GERTi.Register:input_type -> gerti.RegisterNode
	1,  // 6: gerti.GERTi.AnounceNode:input_type -> gerti.NewNode
	7,  // 7: gerti.GERTi.OpenConnection:input_type -> gerti.OpenRoute
	9,  // 8: gerti.GERTi.Data:input_type -> gerti.DataPacket
	5,  // 9: gerti.GERTi.RemoveNeighbor:input_type -> gerti.RemoveNeighborData
	6,  // 10: gerti.GERTi.CloseConnection:input_type -> gerti.CloseConnectionData
	1,  // 11: gerti.GERTi.AnnounceNewNode:output_type -> gerti.NewNode
	4,  // 12: gerti.GERTi.Register:output_type -> gerti.RegisterComplete
	10, // 13: gerti.GERTi.AnounceNode:output_type -> google.protobuf.Empty
	8,  // 14: gerti.GERTi.OpenConnection:output_type -> gerti.RouteOpen
	10, // 15: gerti.GERTi.Data:output_type -> google.protobuf.Empty
	10, // 16: gerti.GERTi.RemoveNeighbor:output_type -> google.protobuf.Empty
	10, // 17: gerti.GERTi.CloseConnection:output_type -> google.protobuf.Empty
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_gerti_proto_init() }
func file_gerti_proto_init() {
	if File_gerti_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gerti_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerti_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewNodeData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerti_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerti_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterComplete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerti_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveNeighborData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerti_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseConnectionData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerti_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenRoute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerti_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteOpen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerti_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_gerti_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*NewNode_Data)(nil),
		(*NewNode_None)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gerti_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gerti_proto_goTypes,
		DependencyIndexes: file_gerti_proto_depIdxs,
		EnumInfos:         file_gerti_proto_enumTypes,
		MessageInfos:      file_gerti_proto_msgTypes,
	}.Build()
	File_gerti_proto = out.File
	file_gerti_proto_rawDesc = nil
	file_gerti_proto_goTypes = nil
	file_gerti_proto_depIdxs = nil
}
